---
- name: "Reload php-fpm"
  become: yes
  service:
    name: "{{ php_fpm_service }}"
    state: reloaded

- name: "Reload nginx"
  become: yes
  service:
    name: nginx
    state: reloaded

- name: "Reload systemd units"
  become: yes
  shell: "systemctl daemon-reload"