---
- name: "Create dir for serveradmin"
  become: yes
  file:
    path: "/home/{{ applications_devmode_user }}/workspace"
    state: directory
    owner: "{{ applications_devmode_user }}"
    group: "{{ applications_devmode_user }}"
  when: applications_devmode

- name: "Mount serveradmin-repo for devmode"
  include_role:
    name: applications
    tasks_from: devmode_repo
  vars:
    application: "{{ serveradmin }}"
    #path: "{{ serveradmin.path }}"
    #process_user: "{{ serveradmin.process_user }}"
    #process_group: "{{ serveradmin.process_group }}"
    repo: "{{ serveradmin.repo | combine({'name': 'serveradmin-devmode'}) }}"
    #name: serveradmin-devmode
    #path: "{{ serveradmin.repo.path }}"
  when: applications_devmode
