---

- name: "Run Composer"
  become: yes
  become_user: "{{ application.process_user }}"
  shell: >-
    /home/system/{{ application.process_user }}/.local/bin/composer install{% if not applications_devmode %} --no-dev --optimize-autoloader{% endif %}
  args:
    chdir: "{{ deploy_facts[deploy.repo | mandatory].source }}/{{ deploy.path_in_repo | d('') }}"
