---
- name: "Create dirs for cron-scripts for application"
  become: yes
  file:
    path: "{{ application.path }}{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default( application.process_user, true ) }}"
    group: "{{ item.group | default( application.process_group, true ) }}"
    setype: "{{ item.setype | default( '_default' ) }}"                  # httpd_sys_content_t
    mode: "{{ item.mode | default('u=rwx,g=rx,o=') }}"
  when: item.when | default(True)
  loop:
    - { path: "/scripts" }
    - { path: "/log/scripts" }

- name: "Create script för commit and push repo"
  become: yes
  template:
    src: "deploy_plugins/cron_commit_and_push_repo/commit_and_push_repo.sh.j2"
    dest: "{{ application.path }}/scripts/commit_and_push-{{ deploy.repo | mandatory }}.sh"
    owner: "{{ application.process_user }}"
    group: "{{ application.process_group }}"
    mode: "u=rwx,g=rx,o=r"
  when: not applications_devmode

- name: "Setup cron-jobb for commit and push repo"
  become: yes
  template:
    src: "deploy_plugins/cron_commit_and_push_repo/commit_and_push_repo.cron.j2"
    dest: "/etc/cron.d/commit_and_push-{{ application.environment }}-{{ application.name }}-{{ deploy.repo }}"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  when: not applications_devmode