---
- set_fact:
    slack_json:
      text: "*{{ application.environment }}-{{ application.name }} deployed by {{ ansible_started_by_user | default(ansible_facts.user_id) }}!*"
      attachments:
        - color: "{{ host_color_html | default('#000000') }}"
          fields:
            - title: "Deployed by"
              value: "{{ ansible_started_by_user | default(ansible_facts.user_id) }}"
              short: true

            - title: Server
              value: "{{ inventory_hostname }}"
              short: true

            - title: Application
              value: "{{ application.name }}"
              short: true

            - title: Environment
              value: "{{ application.environment }}"
              short: true

            - title: Version
              value: >-
                {%- for (key, value) in deploy_facts.items() if value.version is defined -%}
                {%-   if deploy.version_link is defined -%}
                        <{{- deploy.version_link | replace('{tag}', value.version) -}}|{{- value.version -}}>
                {%-   else -%}
                        {{- value.version -}}
                {%-   endif -%}
                {%-   if not loop.last -%}
                        {{- ', ' -}}
                {%    endif -%}
                {%- end for -%}
              short: true

            - title: Used discspace
              value: >-
                {{- diskspace_message -}}
              short: true

            - title: Description
              value: "{{ deploy_facts[deploy.repo].tag_description }}"
              #  {%- for (key, value) in deploy_facts.items() if value.version is defined -%}
              #        {{- value.tag_description -}}
              #  {%-   if not loop.last -%}
              #          {{- ', ' -}}
              #  {%    endif -%}
              #  {%- end for -%}
              short: false

- name: Skapa Lista med commits
  set_fact:
    slack_list_of_commits: >-
      {%- set o = [] -%}
      {%- for repo_name, deploy_fact in deploy_facts.items() if deploy_fact.list_of_commits | d("") != "" -%}
      {{-   o.append({
              'title': 'Commits för '~repo_name,
              'value': deploy_fact.list_of_commits,
              'short': false
          }) -}}
      {%- endfor -%}
      {{- o -}}
- name: Lista alla nya commits med
  set_fact:
    slack_json: >-
      {{- slack_json.attachments.append({
          'color': '#dd37e6',
          'fields': slack_list_of_commits
          }) -}}
      {{- slack_json -}}
  when: slack_list_of_commits|length > 0

#	SLACKFIELDS+=("{\"title\":\"DB\",\"value\":\"${DEPLOY_DBNAMES[$ENVIRONMENT]}\",\"short\":true}")

#	DISKSPACE="$(df / -h | tail -1 | sed -n --regexp-extended 's/^[^\s]+\s+([0-9.]+[MG])\s+([0-9.]+[MG])\s+([0-9.]+[MG])\s+([0-9.]+%)\s+\/$/\2\/\1 (\4)/p')"
#	SLACKFIELDS+=("{\"title\":\"Diskutrymme\",\"value\":\"$DISKSPACE\",\"short\":true}")

#	SLACKFIELDS+=("{\"title\":\"DB Version\",\"value\":\"${DEPLOYED_DBVERSIONS[$ENVIRONMENT]}\",\"short\":false}")

#	SLACK_MESSAGE="*New deployment on server!*"

#	SLACK_JSON="{\"text\":\"$SLACK_MESSAGE\",\"attachments\":[{\"color\":\"#2eb886\",\"fields\":[$(join_by , "${SLACKFIELDS[@]}")]}]}"
#- name: "Post till Slack"
#  shell: "curl -X POST -H 'Content-type: application/json' --data \"{{ slack_json|to_json }}\" {{ deploy.service_hook }}"
- name: "Posta till Slack"
  uri:
    url: "{{ deploy.service_hook }}"
    method: POST
    body: "{{ slack_json }}"
    #status_code: 201
    body_format: json
  when: not applications_devmode
