---

- name: "Remove existing"
  become: yes
  file:
    path: "{{application.path }}/{{ webinstance.root_dir }}"
    state: absent


- name: "Symlink: root dir"
  become: yes
  file:
    path: "{{application.path }}/{{ webinstance.root_dir }}"
    src: "{{ deploy_facts[repo.name].source }}"
    owner: "{{ application.process_user }}"
    group: "{{ application.process_group }}"
    state: link
    force: yes
