---

- name: "Remove existing"
  become: yes
  file:
    path: "{{application.path }}/{{ application.webinstances[deploy.webinstance | mandatory].root_dir }}"
    state: absent


- name: "Symlink: root dir"
  become: yes
  file:
    path: "{{application.path }}/{{ application.webinstances[deploy.webinstance].root_dir }}"
    src: "{{ deploy_facts[deploy.repo_name | mandatory].source }}"
    owner: "{{ application.process_user }}"
    group: "{{ application.process_group }}"
    state: link
    force: yes
