---
#- debug:
#    var: deploy_facts

- name: "Deploy Run Liquibase"
  become: yes
  become_user: "{{ application.process_user }}"
  shell: >-
    {% if deploy.liquibase_in_repo is defined %}{{ deploy_facts[deploy.repo].path }}/{{ deploy.liquibase_in_repo }}{% else %}{{ serveradmin.path }}/repos/serveradmin/tools/liquibase/liquibase{% endif %}
    --driver="org.mariadb.jdbc.Driver"
    --username="{{ application.process_user }}"
    --url="jdbc:mariadb://localhost/{{ application.databases[ deploy.databaseindex | d(0) ].database | mandatory }}?localSocket=/var/lib/mysql/mysql.sock&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Stockholm"
    --changeLogFile="{{ deploy.change_log_file }}"
    --contexts="{{ application.environment }}"
    {{- ' '+item -}}
  args:
    chdir: "{{ deploy_facts[deploy.repo | mandatory].path }}/{{ deploy.change_log_dir }}"
  loop:
    - "update"
    - "tag {{ deploy_facts[deploy.repo].version }}"
