---

- name: "Deploy Symlink root dir (Remove)"
  become: yes
  file:
    path: "{{application.path }}/{{ application.webinstances[deploy.webinstance | mandatory].root_dir }}"
    state: absent


- name: "Deploy Symlink root dir (Create)"
  become: yes
  file:
    path: "{{application.path }}/{{ application.webinstances[deploy.webinstance].root_dir }}"
    src: "{{ deploy_facts[deploy.repo | mandatory].source }}"
    owner: "{{ application.process_user }}"
    group: "{{ application.process_group }}"
    state: link
    force: yes
