---

- name: "Building Vue..."
  debug:
    msg: "Wait..."

- name: "Vue: Confirm @vue/cli is installed. Needs to be installed manually: npm i -g @vue/cli"
  become: yes
  become_user: "{{ application.process_user }}"
  shell:
    cmd: >-
      /bin/bash -lc "npm list --global --no-progress @vue/cli"
    chdir: "{{ deploy_facts[deploy.repo | mandatory].source }}/{{ deploy.path_in_repo | d('') }}"
  ignore_errors: "{{ deploy.ignore_errors | d(false) }}"

- name: "Vue: Install npm-dependencies"
  become: yes
  become_user: "{{ application.process_user }}"
  shell:
    cmd: >-
      /bin/bash -lc "npm install --no-save --no-progress"
    chdir: "{{ deploy_facts[deploy.repo | mandatory].source }}/{{ deploy.path_in_repo | d('') }}"
  ignore_errors: "{{ deploy.ignore_errors | d(false) }}"

- name: "Vue Application Build"
  become: yes
  become_user: "{{ application.process_user }}"
  shell:
    cmd: >-
      /bin/bash -lc "npm run build"
    chdir: "{{ deploy_facts[deploy.repo | mandatory].source }}/{{ deploy.path_in_repo | d('') }}"
  ignore_errors: "{{ deploy.ignore_errors | d(false) }}"