---
- debug:
   var: host_and_job.0

- debug:
    var: host_and_job.1

- debug:
    var: host_and_job

- name: "Force format of folder path to format '/foo/bar', '/foo' or ''"
  set_fact:
    pretty_source: |-
      {{ host_and_job.1.source | regex_replace('^/?(.*?)/?(\./)*$', '/\\1') | regex_replace('/\./', '/') }}
  when: host_and_job.1.type | d('files') in ['files']

- debug:
    var: pretty_source


- name: "Test: Mount the folders to backup under backup_source as read only (bindfs)"
  debug:
    msg: "{{ backup_info.backup_script_output_dir ~  host_and_job.0 }}/{{ backupinstance.value.name }} -- {{ host_and_job.1.source }} -- pretty: {{ pretty_source }}"
  when: host_and_job.1.type | d('files') in ['files']
  loop: "{{ backup_dest_with_public_keys.keys() | product(backupinstance.value.jobs) | list }}"
  loop_control:
     loop_var: host_and_job


# - name: "Mount the folders to backup under backup_source as read only (bindfs)"
#   become: yes
#   mount:
#     src: "{{ host_and_job.1.source }}"
#     path: "{{ backup_info.backup_script_output_dir ~  host_and_job.0 }}/{{ backupinstance.value.name }}"
#     fstype: fuse.bindfs
#     # Dokumentation: man bindfs
#     opts: |-
#       ro                                                             {#- -#}
#       ,force-user={{ backup_info.source_user.name }}                 {#- -#}
#       ,force-group={{ backup_info.source_user.group }}               {#- -#}
#       ,chown-ignore                                                  {#- -#}
#       ,chgrp-ignore                                                  {#- -#}
#     state: mounted
#   when: host_and_job.1.type | d('files') in ['files']
#   loop: "{{ backup_dest_with_public_keys.keys() | product(backupinstance.value.jobs) | list }}"
#   loop_control:
#      loop_var: host_and_job



