---
- name: "Current application in devmode"
  debug:
    var: application

- name: "Clone repo to devmode-user's workspace"
  include_role:
    name: git
    tasks_from: clone_repo
  vars:
    clone_repo:
      dest: "/home/{{ applications_devmode_user }}/workspace/{{ organisation.name }}/{{ repo.name }}"
      user: "{{ applications_devmode_user }}"
      update: false
    repo: "{{ repo | combine( { 'use_unique_deploy_key':false } ) }}"

- name: "Mount the dev repo in the application repo-place"
  mount:
    path: "{{ application.path }}/repos/{{ repo.name }}"
    src: "/home/{{ applications_devmode_user }}/workspace/{{ organisation.name }}/{{ repo.name }}"
    opts: "bind,{{ application.process_user }}"
    state: mounted
    fstype: none