---
- name: "Gather list of nginx conf"
  find:
    paths: "/etc/nginx/conf.d/{{ organisation.name }}/"
    patterns:
      - "*.conf"
  register: current_ngninx_files

- name: "Filter out used nginx confs"
  set_fact:
    files_to_delete: >-
      {%- set valid_files  = [] -%}
      {%- for application in applications_info -%}
      {%-   for name, webinstance in application.webinstances.items() -%}
      {%-     for domaininstance in webinstance.domaininstances -%}
      {{-       valid_files.append('/etc/nginx/conf.d/'+organisation.name+'/'+domaininstance.fullname+'.conf') -}}
      {%-     endfor -%}
      {%-   endfor -%}
      {%- endfor -%}
      {{- current_ngninx_files.files | map(attribute='path') | list | difference(valid_files) -}}

- name: "Remove nginx conf files not part of current applications"
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ files_to_delete }}"
  notify: "Reload nginx"
