---

### devmodes ####################################################################

- name: Repos for devmode
  include_tasks: devmode_repo.yml
  loop: "{{ application.repos }}"
  loop_control:
    loop_var: repo
    label: "{{ repo.name }}"
