---
- name: "Current application in devmode"
  debug:
    var: application

- name: "Create folder for repo"
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | d( 'root', true ) }}"
    group: "{{ item.group | d( 'root', true ) }}"
    setype: "{{ item.setype | default( '_default' ) }}"                  # httpd_sys_content_t
    mode: "{{ item.mode | d('u=rwx,g=rx,o=rx') }}"
  when: item.when | default(True)
  loop:
    - { path: "/home/{{ applications_devmode_user }}/workspace/{{ organisation.name }}/{{ repo.path | basename }}", owner: "{{ applications_devmode_user }}", group: "{{ applications_devmode_user }}" }
    - { path: "{{ application.path }}/repos/{{ repo.name }}", owner: "{{ application.process_user }}", group: "{{ application.process_group }}" }


- name: "Mount the dev repo in the application repo-folder"
  become: yes
  mount:
    path: "{{ application.path }}/repos/{{ repo.name }}"
    src: "/home/{{ applications_devmode_user }}/workspace/{{ organisation.name }}/{{ repo.path | basename }}"
    opts: "iocharset=utf8,sec=ntlm"
    fstype: cifs
    state: mounted
