---
- name: "Current application in devmode"
  debug:
    var: application

# Script fail if we try to create a folder that is already used as a mountpoint, so check if it exists first:
- name: "Check mount point devmode"
  become: yes
  stat:
    path: "{{ application.path }}/devmode/{{ repo.name }}"
  register: mount_point_devmode

- name: "Check mount point repos"
  become: yes
  stat:
    path: "{{ application.path }}/repos/{{ repo.name }}"
  register: mount_point_repos

- name: "Create folder for repo"
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | d( application.process_user, true ) }}"
    group: "{{ item.group | d( application.process_group, true ) }}"
    setype: "{{ item.setype | default( '_default' ) }}"                  # httpd_sys_content_t
    mode: "{{ item.mode | d('u=rwx,g=rx,o=') }}"
  when: item.when | default(True)
  loop:
    - { path: "/home/{{ applications_devmode_user }}/workspace/{{ organisation.name }}/{{ repo.path | basename }}", owner: "{{ applications_devmode_user }}", group: "{{ applications_devmode_user }}" }
    - { path: "{{ application.path }}/devmode/{{ repo.name }}",       when: "{{ not mount_point_devmode.stat.exists }}" }
    - { path: "{{ application.path }}/devmode/{{ repo.name }}-upper" }
    - { path: "{{ application.path }}/devmode/{{ repo.name }}-work"  }
    - { path: "{{ application.path }}/repos/{{ repo.name }}",        when: "{{ not mount_point_repos.stat.exists }}" }

- name: "Mount the dev repo in the application devmode-folder (bindfs)"
  become: yes
  mount:
    src: "/home/{{ applications_devmode_user }}/workspace/{{ organisation.name }}/{{ repo.path | basename }}"
    path: "{{ application.path }}/devmode/{{ repo.name }}"
    fstype: fuse.bindfs
    # Dokumentation: man bindfs
    opts: "ro,force-user={{ application.process_user }},force-group={{ application.process_group }}"
    state: remounted

- name: "Mount the dev repo with overlay in the application repos-folder (overlay)"
  become: yes
  mount:
    src: "overlay"
    path: "{{ application.path }}/repos/{{ repo.name }}"
    fstype: overlay
    # Dokumentation: man mount.cifs
    opts: |-
      x-systemd.after={{ application.path }}/devmode/{{ repo.name }}  {#- Wait for the bindfs to mount Doumentation: https://www.freedesktop.org/software/systemd/man/systemd.mount.html -#}
      ,lowerdir={{ application.path }}/devmode/{{ repo.name }}        {#- The main content of this mount -#}
      ,upperdir={{ application.path }}/devmode/{{ repo.name }}-upper  {#- Where changes from delpoy-script, the webapp it self etc i written. Cleared by _deploy -#}
      ,workdir={{ application.path }}/devmode/{{ repo.name }}-work    {#- Demanded by overlayfs -#}
    state: remounted
