---
- name: "Current application in devmode"
  debug:
    var: application

# Script fail if we try to create a folder that is already used as a mountpoint, so check if it exists first:
- name: "Check mount point"
  become: yes
  stat:
    path: "{{ application.path }}/repos/{{ repo.name }}"
  register: mount_point

- name: "Create folder for repo"
  become: yes
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | d( 'root', true ) }}"
    group: "{{ item.group | d( 'root', true ) }}"
    setype: "{{ item.setype | default( '_default' ) }}"                  # httpd_sys_content_t
    mode: "{{ item.mode | d('u=rwx,g=rx,o=rx') }}"
  when: item.when | default(True)
  loop:
    - { path: "/home/{{ applications_devmode_user }}/workspace/{{ organisation.name }}/{{ repo.path | basename }}", owner: "{{ applications_devmode_user }}", group: "{{ applications_devmode_user }}" }
    - { path: "{{ application.path }}/repos/{{ repo.name }}", owner: "{{ application.process_user }}", group: "{{ application.process_group }}", when: "{{ not mount_point.stat.exists }}" }


- name: "Mount the dev repo in the application repo-folder"
  become: yes
  mount:
    src: "//localhost/workspace/{{ organisation.name }}/{{ repo.path | basename }}"
    path: "{{ application.path }}/repos/{{ repo.name }}"
    fstype: cifs
    # Dokumentation: man mount.cifs
    opts: "guest,iocharset=utf8,vers=3,uid={{ application.process_user }},gid={{ application.process_group }},noauto,x-systemd.automount"
    state: mounted
