---
- name: "Reload php-fpm"
  become: yes
  service:
    name: "{{ php_fpm_service }}"
    state: reloaded
  # If there is no php-fpm-pools, this will fail... Ignore and continue
  ignore_errors: true

- name: "Reload nginx"
  become: yes
  service:
    name: nginx
    state: reloaded

- name: "Reload systemd units"
  become: yes
  shell: "systemctl daemon-reload"