---
- name: Kör liquibase  
  shell: >-
    {{ serveradmin.path }}/workspace/serveradmin/tools/liquibase/liquibase
    --driver="org.mariadb.jdbc.Driver"
    --username="{{ serveradmin.process_user }}"
    --url="jdbc:mariadb://localhost/{{ webinstance.database }}?localSocket=/var/lib/mysql/mysql.sock&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Europe/Stockholm"
    --changeLogFile="{{ deploy.change_log_file }}"
    {{- ' '+item -}}
  args:
    chdir: "{{ deploy_facts[repo.name].repo_source }}/{{ deploy.change_log_dir }}"
  loop:
    - "update"
    - "tag {{ deploy_facts[repo.name].version }}"

    
