---
- name: "Skapa mapp för repo i /versions"
  become: yes
  file:
    path: "{{ webinstance.path }}/versions/{{ repo.name }}"
    state: directory
    owner: "{{ webinstance.process_user }}"
    group: "{{ webinstance.process_group }}"
    # setype: "{{ item.setype | default( '_default' ) }}"                  # httpd_sys_content_t
    mode: "u=rwx,g=rx,o=rx"


- name: "Uppdatera deploy_facts med [repo.name].source" 
  set_fact:
    deploy_facts: >-
      {{- deploy_facts | combine({
        repo.name: {
            'source': webinstance.path+'/versions/'+repo.name+'/'+deploy_facts[repo.name].version
          }
        }
        , recursive=True) -}}

#- debug:
#    var: deploy_facts
#- pause:


#setype: httpd_sys_rw_content_t om nginx ska skriva...

- name: "Kopiera filer till /versions"
  become: yes
  become_user: "{{ webinstance.process_user }}"
  # Don't use cp, rsync is easier with exclude-list
  #cp -r 'web'/ "${DEPLOY_PATH}_${DEPLOY_TAG}"
  
  #rsync:
  #-a, --archive               archive mode; equals -rlptgoD (no -H,-A,-X)
  #  -r, --recursive             recurse into directories
  #  -l, --links                 copy symlinks as symlinks
  #  -p, --perms                 preserve permissions
  #  -t, --times                 preserve modification times
  #  -g, --group                 preserve group
  #  -o, --owner                 preserve owner (super-user only)
  #  -D                          same as --devices --specials
  #    --devices               preserve device files (super-user only)
  #    --specials              preserve special files
  
  #  -H, --hard-links     This tells rsync to look for hard-linked files in the transfer and link together the corresponding files on the receiving side. Without this option, hard-linked files in the transfer are treated as though they were separate files.
  #  -A, --acls           This option causes rsync to update the destination ACLs to be the same as the source ACLs. The option also implies --perms.
  #  -X, --xattrs         This option causes rsync to update the remote extended attributes to be the same as the local ones.
  
  #-v, --verbose
  #-z, --compress              compress file data during the transfer
  shell: "rsync -a --delete {{ '--exclude-from '+dq+deploy.exclude_list_file+dq+' ' if deploy.exclude_list_file is defined else '' }}'{{ deploy.folder_to_copy }}'/ \"{{ deploy_facts[repo.name].source }}\""
  args:
    chdir: "{{ deploy_facts[repo.name].repo_source }}"
  vars:
    dq: >-
      "
