---

- name: "Symlink: replace_existing"
  become: yes
  file:
    path: "{{ deploy_facts[repo.name].source }}/{{ item.from }}"
    state: absent
  when: deploy.replace_existing
  loop: "{{ deploy.symlinks }}"

- name: "Symlink: replace_existing"
  become: yes
  file:
    path: "{{ deploy_facts[repo.name].source }}/{{ item.from }}"
    src: "{{ webinstance.path }}/{{ item.to }}"
    owner: "{{ webinstance.process_user }}"
    group: "{{ webinstance.process_group }}"
    state: link
    force: "{{ deploy.replace_existing }}"
  loop: "{{ deploy.symlinks }}"
