---

- name: "Install NFS (YUM)"
  become: yes
  yum:
    name:
      - nfs-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: "Create /etc/exports for NFS"
  become: yes
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: "Reload NFS"

- name: "Ensure NFS is running"
  become: yes
  service:
    name: "nfs-server"
    state: started
    enabled: yes
  when: nfs.exports | length
