---

- name: "Install NFS (YUM)"
  become: yes
  yum:
    name:
      - nfs-utils
    state: present
  when: ansible_os_family == "RedHat"

- block:
  - name: "Get uid for owner of exports"
    getent:
      database: passwd
      key: "{{ item }}"
  - set_fact:
      nfs_exports_owner: "{{ nfs_exports_owner | d({}) | combine({ item : { 'uid': getent_passwd[item][1], 'gid': getent_passwd[item][2] }})" 
  loop: "{{ nfs.exports | selectattr('owner', 'defined') | map(attribute='owner') | unique | list }}"

- debug:
    var: "nfs_exports_owner"

- fail:

- name: "Create /etc/exports for NFS"
  become: yes
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: "Reload NFS"

- name: "Ensure NFS is running"
  become: yes
  service:
    name: "nfs-server"
    state: started
    enabled: yes
  when: nfs.exports | length
