---
#- name: Lägg unix användare för access till mariadb
#  include_role:
#    name: mariadb
#    tasks_from: create_user
#  vars:
#    user:
#      [is_linux_user: default(false)] # Gör att det går att logga in utan lösenord för användaren (unix_socket)
#      name: "användarenamn" #Användarnamnet på användaren (kan vara linux användare)
#      [password: sätt lösenord, annars default unix_socekt om linux-användare] 
#      [host: default(localhost)]
#      [sudoer: default(false)
#      [databases:
#        - database: databasename
#          [table: tablename | default("*")]
#          [privileges: privilege, privilege... | default('ALL PRIVILEGES')] (Från: https://mariadb.com/kb/en/library/grant/ )
# Borttagna:
#      [database: default("*")]
#      [grant_all_privileges: default(false)

#- debug:
#    var: user

- set_fact:
    user_temp: |-
      {{- {
      'is_linux_user': false,
      'is_superadmin': user.sudoer | default(false),
      'host': 'localhost',
      'databases': []
      } | combine(user) -}}

- name: Ta reda på huvudgruppen för användaren
  command: id -gn
  become: yes
  become_user: "{{ user_temp.name }}"
  register: mariadb_create_user_primary_group_result
  changed_when: false
  when: user_temp.is_linux_user

# 2019-12-30 LL Not needed when using unix-socket
#- name: config my.cnf
#  become: yes
#  template:
#    src: my.cnf.j2
#    owner: "{{ user_temp.name }}"
#    group: "{{ mariadb_create_user_primary_group_result.stdout }}"
#    dest: "~{{ user_temp.name }}/.my.cnf"
#    mode: "u=rw,g=,o="
#  when: user_temp.is_linux_user

- name: "Finns användaren?"
  become: yes
  command: >-
    mysql -u root -N -B -e "SELECT CONCAT('user ','exists') AS myuser FROM mysql.user WHERE user = '{{ user_temp.name }}' AND Host = '{{ user_temp.host }}'"
  register: existing_user
  changed_when: not 'user exists' in existing_user.stdout

- name: "Set identified_via"
  set_fact:
    # använder mysql_native_password istället för ed25519 på grund av följande bugg: https://jira.mariadb.org/browse/MDEV-19807
    identified_via: >-
      {%- set output = [] -%}
      {%- if user_temp.password is defined -%}
      {{-   output.append("mysql_native_password USING PASSWORD('"+user_temp.password+"')") -}}
      {%- endif -%}
      {%- if user_temp.is_linux_user -%}
      {{-   output.append('unix_socket') -}}
      {%- endif -%}
      {%- if output -%}
      {{ ' ' }}IDENTIFIED VIA {{ output | join(' OR ') }}
      {%- endif -%}

- name: Skapa databas-användaren
  become: yes
  command: >-
      mysql -u root -e "CREATE USER '{{ user_temp.name }}'@'{{ user_temp.host }}'{{ identified_via }}"
  when: existing_user.changed

- name: Uppdatera databas-användaren
  become: yes
  command: >-
      mysql -u root -e "ALTER USER '{{ user_temp.name }}'@'{{ user_temp.host }}'{{ identified_via }}"
  when: not existing_user.changed
  changed_when: false # Vi vet inte denna uppdaterar något eller inte. Troligen inte...

- name: "GRANT ALL PRIVILEGES (superadmin)"
  become: yes
  command: >-
    mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO '{{ user_temp.name }}'@'{{ user_temp.host }}' WITH GRANT OPTION;"
  when: user_temp.is_superadmin
  changed_when: existing_user.changed # Vi vet inte denna uppdaterar något eller inte. Troligen om det är ny använader

- name: "GRANT SUPER (superadmin)"
  become: yes
  command: >-
    mysql -u root -e "GRANT SUPER ON *.* TO '{{ user_temp.name }}'@'{{ user_temp.host }}';"
  when: user_temp.is_superadmin
  changed_when: existing_user.changed # Vi vet inte denna uppdaterar något eller inte. Troligen om det är ny använader

- name: "Ge access till databaser (och tables)"
  become: yes
  command: >-
    mysql -u root -e "GRANT {{ item.privileges | default('ALL PRIVILEGES', true) }} ON {{ item.database }}.{{ item.table | default('*') }} TO '{{ user_temp.name }}'@'{{ user_temp.host }}';"
  loop: "{{ user_temp.databases }}"
