---
### Fix för jmespath ####################################################################
- name: "Fix: You need to install \"jmespath\" prior to running json_query filter"
  become: yes
  yum:
    name:
      - python-pip
    state: latest
  delegate_to: 127.0.0.1
  when: ansible_os_family == "RedHat"

- pip:
    chdir: /usr/lib/python2.7/dist-packages/ansible
    name: jmespath
  delegate_to: 127.0.0.1

### CentOS Package ######################################################################

# https://cloud.google.com/sdk/docs/quickstart-redhat-centos
- name: Install Google Cloud SDK repo (RedHat).
  become: yes
  yum_repository:
    name: "Google-Cloud-SDK"
    description: "A set of command-line tools for the Google Cloud Platform. It contains gcloud, gsutil, and bq, which you can use to access Google Compute Engine, Google Cloud Storage, Google BigQuery, and other products and services."
    baseurl: "https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64"
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
    state: present
  when: ansible_distribution_file_variety == "RedHat"

# Behövs fler?
# https://github.com/leucos/ansible-gcloud/blob/master/tasks/gcloud.yml
- name: Install packages for RedHat-family (YUM)
  become: yes
  yum:
    name:
      - google-cloud-sdk
    state: latest
  when: ansible_os_family == "RedHat"


