---
# Usage:
#
#- include_tasks: get_webinstance.yml
#  vars:
#     active_webinstance: "{ ett item från active_webinstances }"
#
# Returnerar: webinstance


- fail:
    msg: "Kontroll: {{ active_webinstance.name }} saknas i webinstances"
  when: active_webinstance.name not in webinstances

### Samla information ####################### #########################################
- name: Hämta värden från active_webinstance och sätt default
  set_fact:
    webinstance_temp: >-
      {{ { 'process_user': 'www-'+active_webinstance.environment+'-'+active_webinstance.name,
           'process_group': 'www-'+active_webinstance.environment+'-'+active_webinstance.name,
           'enable_https': false,
           'enable_php': false,
           'enable_redis': false,
           'root_dir': 'public_html',
           'create_root_dir': false,
           'backup_database': [],
           'repos': [],
           'upload_max_filesize': '1M',
           'domains_source': {},
           'fastcgi_params': {
             'domain_instance':{},
             'web_instance':{}
           },
           'nginx_includes': {}
         } | combine(webinstances[active_webinstance.name], recursive=True) | combine(active_webinstance, recursive=True) }}

### Hämta domännamn ###
- set_fact:
    domaininstances_result: false

- name: Hämta domännamn från databas
  include_tasks: get_webinstance_domains_from_sql.yml
  when: webinstance_temp.domains_source.sql_domaininstances is defined

- set_fact:
    repo_urls: "{{ [] }}"

- include_role:
    name: serveradmin
    tasks_from: get_repo_url
  vars:
    repo: "{{ item }}"
    repo_url_loop: true
  loop: "{{ webinstance_temp.repos }}"

- name: Returnerar webinstance 
  set_fact:
    webinstance: |-
      {%- set o =  {} -%}
      {%- for key, value in webinstance_temp.items() if key != 'domaininstances' -%}
      {{-   o.__setitem__(key, value) -}}
      {%- endfor -%}
      {%- if domaininstances_result is iterable -%}
      {{-   o.__setitem__('domaininstances', domaininstances_result) -}}
      {%- elif active_webinstance.domaininstances is defined -%}
      {{-   o.__setitem__('domaininstances', active_webinstance.domaininstances) -}}
      {%- else -%}
      {{-   o.__setitem__('domaininstances', webinstances[active_webinstance.name].domaininstances | default([])) -}}
      {%- endif -%}
      {%- for i in o.domaininstances if i.instance is not defined -%}
      {{-   i.__setitem__('instance', 'default_'+loop.index0|string) -}}
      {%- endfor -%}
      {{- o.__setitem__('fullname', o.environment+'-'+o.name) -}}
      {%- if o.path is not defined -%}
      {{-   o.__setitem__('path', '/opt/'+organisation.name+'/'+o.fullname) -}}
      {%- endif -%}
      {%- for domaininstance in o.domaininstances -%}
      {{-   domaininstance.__setitem__('fullname', o.fullname+'-'+domaininstance.instance) -}}
      {%- endfor -%}
      {%- for repo in o.repos -%}
      {{-   repo.__setitem__('url', repo_urls[loop.index0]) -}}
      {%- endfor -%}
      {{- o -}}

- name: Aktuell webinstans
  debug:
    var: webinstance
