---
single_quote: "'"
double_quote: '"'
php_package: php
php_fpm_service: php-fpm
php_fpm_pool_path: /etc/php-fpm.d
nginx_user: nginx
nginx_group: nginx

applications_devmode: false

applications_devmode_samba: true
applications_devmode_nfs: false
applications_devmode_use_overlayfs: false

webserver_use_ssl: true
webserver_use_letsencrypt: "{{ (not applications_devmode) and webserver_use_ssl }}"
applications_enable_https_by_default: true


applications_default:
  # To use this applikationen,
  # in host_vars:
  #application_instances:
  #  - name: defaultnoresponse
  defaultnoresponse:
    desc: "Servern ger tomt svar på anrop till ip eller okänd domän."
    environment: system
    organisation: serveradmin
    webinstances:
      web:
        domaininstances:
          - domains: ["_"]
            default_server: true
        enable_https: true
        enable_http2: false
        only_https: false
        cert_handler: "selfsigned"
        nginx_includes:
          rootlocation: "return 444;"

  # To use this applikationen,
  # in host_vars:
  #application_instances:
  #  - name: devmode_infopagee
  devmode_infopage:
    desc: "Devmode infopage as default response."
    environment: system
    organisation: serveradmin
    webinstances:
      web:
        domaininstances:
          - domains: ["_"]
            default_server: true
        enable_https: true
        enable_http2: false
        only_https: false
        cert_handler: "selfsigned"
        root_dir: public_html
        create_root_dir: true
    deploy:
      - plugin: devmode_infopage
        webinstance: web

  #För att använda denna applikationen,
  # i host_vars:
  #application_instances:
  #  - name: nextcloud
  #    [organisation: {orgname}]
  #    environment: cloud_tvartom_com
  #    desc: "Nextcloud ({domain})"
  #  webinstances:
  #    web:
  #      domaininstances:
  #        - domains:
  #            - {domain}
  #  [process_user: "{user}"]
  #  [process_group: "{group}}"
  #  [path: "{path}"]
  #  database:
  #    name: nextcloud
  #    [create: true]
  #  metadata:
  #    nextcloud:
  #      version: 18.0.0
  #      datadir: "{data path}"
  #      [datadir_external:]
  #        - "{external data path}"
  nextcloud:
    webinstances:
      web:
        use_custom_nginx_include_file: true
        enable_php: true
        enable_https: true
        enable_http2: true
        upload_max_filesize: 16G
    enable_redis: true
    deploy:
      - plugin: nextcloud
        webinstance: web

  wordpress:
    webinstances:
      web:
        create_root_dir: true
        root_dir: wordpress
        #use_custom_nginx_include_file: true
        enable_php: true
        enable_https: true
        enable_http2: true
        # upload_max_filesize: 16G
        wordpress: true
    #enable_redis: true
    deploy:
      - plugin: wordpress
        webinstance: web
