---
- include_role:
    name: applications
    tasks_from: default_values
    public: yes

- name: Install xdebug for php (APT)
  become: yes
  apt:
    name:
      - "{{ php_package }}-xdebug"
    state: present
    install_recommends: yes
    update_cache: yes
    cache_valid_time: 600
  when: ansible_os_family == "Debian"
  notify: "Reload php-fpm"

- name: Install xdebug for php (DNF)
  become: yes
  dnf:
    name:
      - "{{ php_package }}-xdebug"
    state: present
  when: ansible_os_family == "RedHat"
  notify: "Reload php-fpm"

- name: "xdebug php-ini"
  become: yes
  lineinfile:
    path: "{{ php_xdebug_ini }}"
    regexp: '^;?{{ item.option }} ='
    line: "{{ item.option }} = {{ item.value }}"
  loop:
    - option: xdebug.remote_enable
      value: 1
    - option: xdebug.remote_autostart
      value: 1
    # https://xdebug.org/docs/display
    - option: xdebug.overload_var_dump
      value: 0
    # https://xdebug.org/docs/all_settings#remote_connect_back
    - option: xdebug.remote_connect_back
      value: 1
  notify: "Reload php-fpm"
