---
#- include_role:
#    name: dnf_module
#    tasks_from: install_package_from_module
#  vars:
#    dnf:
#      module_name: nginx
#      module_spec: "1.16"
#      packages:
#        - nginx

- name: "List enabled module (DNF)"
  become: yes
  shell:
    cmd: >-
      dnf module list --enabled {{ dnf.module_name }} | grep "^{{ dnf.module_name }}"
  register: module_list_enabled
  changed_when: dnf.module_spec|string  not in module_list_enabled.stdout
  tags:
    - always

- name: "Uninstall present packages (DNF)"
  become: yes
  dnf:
    name: "{{ dnf.packages }}"
    state: absent
  when: dnf.module_spec|string not in module_list_enabled.stdout
  tags:
    - always

- name: "Reset module (DNF)"
  become: yes
  shell:
    cmd: "dnf module reset -y {{ dnf.module_name }}"
  when: dnf.module_spec|string not in module_list_enabled.stdout
  tags:
    - always

- name: "Enable module (DNF)"
  become: yes
  shell:
    cmd: "dnf module enable -y {{ dnf.module_name }}:{{ dnf.module_spec }}"
  when: dnf.module_spec|string not in module_list_enabled.stdout
  tags:
    - always

- name: "Install package (DNF)"
  become: yes
  yum:
    name: "{{ dnf.packages }}"
    state: present
  tags:
    - always
