---
- include_role:
    name: applications
    tasks_from: default_values
    public: yes

- include_role:
    name: dnf_module
    tasks_from: install_package_from_module
  vars:
    dnf:
      module_name: php
      module_spec: "{{ webserver_php_version }}"
      packages:
        - "{{ php_package }}-fpm"
        - "{{ php_package }}-mysqlnd" # 2019-12-30 LL Moved from mariadb
        - "{{ php_package }}-cli" # 2020-10-14 LL Needed for composer
        # - "{{ php_package }}-mcrypt" #Deprecated, removed from 7.2, OpenSSL used instead.
        #- "{{ php_package }}-mbstring" #Add to application.linux_packages when needed
        #- "{{ php_package }}-cli"  #Add to application.linux_packages when needed
        #- "{{ php_package }}-json" #Add to application.linux_packages when needed
        #- "{{ php_package }}-simplexml" #Add to application.linux_packages when needed
        #- "{{ php_package }}-curl" #Add to application.linux_packages when needed
        #- "{{ php_package }}-gd" #Add to application.linux_packages when needed
        #- "{{ php_package }}-bcmath" # 2020-02-23 LL Behövs av CiviCRM, Add to application.linux_packages when needed
  when: ansible_os_family == "RedHat"

- include_role:
    name: dnf_module
    tasks_from: install_package_from_module
  vars:
    dnf:
      module_name: php
      module_spec: "{{ webserver_php_version }}"
      packages:
        - "{{ php_package }}-opcache"
  when: ansible_os_family == "RedHat" and not applications_devmode

- name: Install extra packages for PHP FastCGI Process Manager (YUM)
  become: yes
  yum:
    name:
      # För att kunna anropa php-fpm utan nginx:
      # https://maxchadwick.xyz/blog/getting-the-php-fpm-status-from-the-command-line
      - fcgi
    state: present
  when: ansible_os_family == "RedHat"

- name: Install PHP FastCGI Process Manager (APT)
  become: yes
  apt:
    name:
      - "{{ php_package }}-fpm"
      - "{{ php_package }}-mysqlnd" # 2019-12-30 LL Moved from mariadb
      # - "{{ php_package }}-mcrypt" #Deprecated, removed from 7.2, OpenSSL used instead.
      #- "{{ php_package }}-mbstring"
      #- "{{ php_package }}-cli"
      #- "{{ php_package }}-json"
      #- "{{ php_package }}-simplexml"
      #- "{{ php_package }}-curl"
      #- "{{ php_package }}-gd"
      #- "{{ php_package }}-bcmath" # 2020-02-23 LL Behövs av CiviCRM
    install_recommends: yes
    update_cache: yes
    cache_valid_time: 600
    state: present
  when: ansible_os_family == "Debian"


- name: Remove Default www.conf
  become: yes
  shell: mv {{ php_fpm_pool_path }}/www.conf {{ php_fpm_pool_path }}/www.conf.removed$(date +"%Y%m%d").ansible
  args:
    removes: "{{ php_fpm_pool_path }}/www.conf"

- name: "Fix umask for php"
  become: yes
  copy:
    src: php-fpm.service.d_override.conf
    dest: /etc/systemd/system/{{ php_fpm_service }}.service.d/override.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Autostart php-fpm
  become: yes
  service:
    name: "{{ php_fpm_service }}"
    enabled: yes
