---
- name: "Create /opt/letsencrypt"
  become: yes
  file:
    path: /opt/letsencrypt
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"

- name: Install acme-tiny-script
  become: yes
  copy:
    src: "acme-tiny"
    dest: "/opt/letsencrypt"
    directory_mode: o=rwX,g=,o=

#- name: Download cert to put in chained file (To be used with Nginx)
#  become: yes
#  get_url:
#    url: https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem
#    dest: /opt/letsencrypt/intermediate.pem
#    mode: u=rw,g=r,o=r

- name: "Generate Letsencrypt account key"
  become: yes
  shell: openssl genrsa 4096 > /opt/letsencrypt/account.key
  args:
    creates: /opt/letsencrypt/account.key

- name: "Create /etc/nginx/ssl"
  become: yes
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"

# https://cipherli.st/
- name: "Warning"
  debug:
    msg: "If dhparam.pem not exists, it will be created now. It takes a long time."

- name: Generate a stronger DHE parameter (This is going to take a long time)
  become: yes
  shell: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 4096
  args:
    creates: /etc/nginx/ssl/dhparam.pem


