---
- name: Install PHP FastCGI Process Manager (YUM)
  become: yes
  yum:
    name:
      - "{{ php_package }}-fpm"
      # - "{{ php_package }}-mcrypt" #Deprecated, removed from 7.2, OpenSSL used instead.
      - "{{ php_package }}-mbstring"
      - "{{ php_package }}-cli"
      - "{{ php_package }}-json"
      - "{{ php_package }}-simplexml"
      - "{{ php_package }}-curl"
      - "{{ php_package }}-gd"
      - "{{ php_package }}-mysqlnd" # 2019-12-30 LL Moved from mariadb
      - "{{ php_package }}-bcmath" # 2020-02-23 LL Behövs av CiviCRM
      # För att kunna anropa php-fpm utan nginx:
      # https://maxchadwick.xyz/blog/getting-the-php-fpm-status-from-the-command-line
      - fcgi
    # update_cache: yes
    state: present
  when: ansible_os_family == "RedHat"

- name: Install PHP FastCGI Process Manager (APT)
  become: yes
  apt:
    name:
      - "{{ php_package }}-fpm"
      # - "{{ php_package }}-mcrypt" #Deprecated, removed from 7.2, OpenSSL used instead.
      - "{{ php_package }}-mbstring"
      - "{{ php_package }}-cli"
      - "{{ php_package }}-json"
      - "{{ php_package }}-simplexml"
      - "{{ php_package }}-curl"
      - "{{ php_package }}-gd"
      - "{{ php_package }}-mysqlnd" # 2019-12-30 LL Moved from mariadb
      - "{{ php_package }}-bcmath" # 2020-02-23 LL Behövs av CiviCRM
    install_recommends: yes
    update_cache: yes
    cache_valid_time: 600
    state: present
  when: ansible_os_family == "Debian"


- name: Remove Default www.conf
  become: yes
  shell: mv {{ php_fpm_pool_path }}/www.conf {{ php_fpm_pool_path }}/www.conf.removed$(date +"%Y%m%d").ansible
  args:
    removes: "{{ php_fpm_pool_path }}/www.conf"

- name: "Fix umask for php"
  become: yes
  copy:
    src: php-fpm.service.d_override.conf
    dest: /etc/systemd/system/{{ php_fpm_service }}.service.d/override.conf
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Autostart php-fpm
  become: yes
  service:
    name: "{{ php_fpm_service }}"
    enabled: yes



# Role webinstances fixar induviduella pooler för var sida!!!

#- name: Use socket instead of tcp
#  become: yes
#  lineinfile:
#    dest: /etc/php-fpm.d/www.conf
#    state: present
#    regexp: "^\s*listen\s*="
#    line: "listen = "

#- name: "Config PHP FastCGI via socket"
#  become: yes
#  lineinfile:
#    dest: /etc/php-fpm.d/www.conf
#    state: present
#    regexp: "^;?\s*{{ item.key }}"
#    line: "{{ item.key }} = {{ item.value }}"
#  with_items:
#    - { key: "listen", value: "/var/run/php-fpm.sock" }
#    - { key: "listen.owner", value: "nginx" } # The user nginx is running by
#    - { key: "listen.group", value: "nginx" }
#    - { key: "listen.mode", value: "0660" }
#    - { key: "catch_workers_output", value: "yes" } # Log to /var/log/php-fpm




