---
- name: Install msmtp (DNF)
  become: yes
  dnf:
    name:
      #- "sendmail"
      - msmtp
    state: present
  when: ansible_os_family == "RedHat"

#- name: Allow sendmail (SE-Linux)
#  become: yes
#  seboolean:
#    name: httpd_can_sendmail
#    state: yes
#    persistent: yes
#  tags:
#    - web

