---
- hosts: "{{ target }}"
  connection: "{{ connection_type | default('ssh', true) }}"
  gather_facts: yes
  collections:
    - tvartom.serveradmin
  tasks:
    # Get data from the host with sensible information, (eg password, private key)
    # This role can also read variables from files, but is not used.
    - name: "Collect facts"
      include_role:
        name: collect_facts
        tasks_from: collect_facts
      vars:
        facts_options:
          var_files: []# Read variables from files in var/[item].yml
            #- system
            #  - webinstances
            #- users
          host_vars_from_host: true
          diskspace_message: false

    - include_role:
        name: basic_centos_tools
      tags:
        - bootstrap

    - include_role:
        name: mc
      tags:
        - bootstrap

    - include_role:
        name: git
      tags:
        - bootstrap

    - include_role:
        name: users
      tags:
        - bootstrap

    - include_role:
        name: mariadb

    - include_role:
        name: firewall

    - include_role:
        name: java_and_maven

    - include_role:
        name: serveradmin
      tags:
        - bootstrap

    - include_role:
        name: webserver

    - name: "Install samba"
      become: true
      import_role:
        name: bertvv.samba
      when: applications_devmode
      vars:
        samba_shares:
          - name: "workspace"
            # comment: 
            path: "/home/{{ applications_devmode_user }}/workspace"
            read_only: no
            write_list: "{{ application_devmode_user }}"
            owner: "{{ application_devmode_user }}"
            group: "{{ application_devmode_user }}"
            setype: httpd_sys_rw_content_t
        samba_users:
          - name: "{{ applications_devmode_user }}"
            password: "dev"

    - include_role:
        name: autofs
      when: autofs is defined

