---
- hosts: "{{ target }}"
  connection: "{{ connection_type | default('ssh', true) }}"
  gather_facts: yes
  collections:
    - tvartom.serveradmin
  tasks:
    # Get data from the host with sensible information, (eg password, private key)
    # This role can also read variables from files, but is not used.
    - name: "Collect facts"
      include_role:
        name: collect_facts
        tasks_from: collect_facts
      vars:
        facts_options:
          var_files: []# Read variables from files in var/[item].yml
            #- system
            #  - webinstances
            #- users
          host_vars_from_host: true
          diskspace_message: false

    - include_role:
        name: basic_centos_tools
      tags:
        - bootstrap

    - include_role:
        name: mc
      tags:
        - bootstrap

    - include_role:
        name: git
      tags:
        - bootstrap

    - include_role:
        name: users
      tags:
        - bootstrap

    - include_role:
        name: mariadb

    - include_role:
        name: firewall

    - include_role:
        name: java_and_maven

    - include_role:
        name: serveradmin
      tags:
        - bootstrap

    - include_role:
        name: webserver

    - include_role:
        name: bertvv_samba
      when: applications_devmode and applications_devmode_samba | d(true)
      vars:
        ansible_become: yes
        samba_shares:
          - name: "workspace"
            comment: "Workspace for devmode"
            path: "/home/{{ applications_devmode_user }}/workspace"
            public: true
            browseable: true
            guest_ok: true
            writeable: true
#            write_list: "{{ applications_devmode_user }}"
            owner: "{{ applications_devmode_user }}"
            group: "{{ applications_devmode_user }}"
            setype: httpd_sys_rw_content_t
            create_mode: '0640'
            #force_create_mode: '0660'
            directory_mode: '0750'
            #force_directory_mode: '0770'
        samba_users:
          - name: "{{ applications_devmode_user }}"
            password: ""
        samba_netbios_name: "{{ inventory_hostname }}"

    - include_role:
        name: nfs
      when: applications_devmode and applications_devmode_nfs | d(false)
      vars:
        nfs:
          exports:
            - comment: "Workspace for devmode"
              path: "/home/{{ applications_devmode_user }}/workspace"
              rw: true
              owner: "{{ applications_devmode_user }}"
              group: "{{ applications_devmode_user }}"
              async: true
              fsid: root

    - include_role:
        name: autofs
      when: autofs is defined

